/*
 * Bounce.c
 *
 *  Created on: Nov. 15, 2019
 *  	Name : Bounce.c
 *      Author: tamara
 *      Description : The program print the values generated by the simulation of
 *      a ball bouncing until it stops.
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define g 9.8 					// gravitational constant
#define pi  3.141592654			//pi value
#define DELTA 0.1				// Clock tick duration (sec)
#define ETHR 0.01				//Threshold
#define k 0.0016				//Chosen constant for the assignment
#define false 0
#define true !false

/**
 * The program reads 4 arguments inserted by the user:
 * Vo: a double corresponding to the initial velocity in meters/seconds
 * theta : a double representing the launch angle of the ball
 * lossValue: a double corresponding to the energy loss on each bounce
 * bSize : a double corresponding to the radius of the sphere (the ball)
 *
 *
 */
int main(void){

	double Vo, theta, lossValue, bSize;
	double Vox, Voy, Vt, KEx, KEy;
	double X, Y, Xlast, Ylast, Vy, Vx, t, Xinit, Xo;

printf("Enter the initial velocity of the ball in meters/seconds [0,100]: "); //prompt
scanf("%lf",&Vo);															  //get data from the user (the initial velocity)

printf("Enter the launch angle in degrees [0,90]: ");						 //prompt
scanf("%lf",&theta);														//get data from the user (launch angle)

printf("Enter the energy loss parameter [0,1]: ");							//prompt
scanf("%lf",&lossValue);													//get data from the user (energy loss coefficient)

printf("Enter the radius of the ball in meters [0.1,5]: ");					//prompt
scanf("%lf",&bSize);														//get data from the user (ball radisu)

Vt = g/(4*pi*bSize*bSize*k);			//terminal velocity
t = 0;
KEx = ETHR;
KEy = ETHR;

Xinit = 5.0;
Vox = Vo*cos(theta*pi/180);				// X component of initial velocity
Voy = Vo*sin(theta*pi/180);				// Y component of initial velocity
Y = bSize;
Ylast = Y;

//start of the simulation
while(true){
	X = Vox*Vt/g*(1-exp(-g*t/Vt))+Xinit ;					// X position during simulation
	Y = (bSize + Vt/g*(Voy+Vt)*(1-exp(-g*t/Vt))-Vt*t);		// Y position during simulation

	Vy = (Y-Ylast)/DELTA;						//Estimate Vx from difference
	Vx = (X-Xlast)/DELTA;						//Estimate Vy from difference
	//print the values of the time, X, Y, Vx and Vy
	if (true) printf("t: %.2f  X: %.2f  Y: %.2f  Vx: %.2f  Vy: %.2f\n", t,X,Y,Vx,Vy);

	Xlast = X;
	Ylast = Y;

	if (Y<=2*bSize && Vy<0){
		KEx = 0.5*Vx*Vx*(1-lossValue); 			//change of kinetic energy in X direction
		KEy = 0.5*Vy*Vy*(1-lossValue);			//change of the kinetic energy in Y direction

		Vox = sqrt(KEx*2);         //X component of initial velocity affected by the loss of energy
		Voy = sqrt(KEy*2);         //Y component of initial velocity affected by the loss of energy
		t=0;
		Y = bSize;
		Xinit = X;			//change of Xinit for the next paraboola
		Xlast = X;
		Ylast = Y;

		}

	if ((KEy<ETHR) | (KEx <ETHR)) break; //condition for the simulation to break and to stop
										 //printing the values

	t+=DELTA;								//update of the time

	}


}

